# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

# Copier uniquement le package.json et le lock file (si vous l'utilisez)
COPY package.json package-lock.json ./

# Installation des dépendances
RUN npm install

# NE PAS copier le code source ici
# car on va le monter en volume pour le hot reload

# Commande de démarrage : mode dev
CMD ["npm", "run", "dev"]
